services:
  nginx:
    image: nginx
  varnish:
    build: .
    links:
        - nginx:nginx
    ports:
        - 80:80
    environment:
        HOST: "nginx:80"
        PUBLIC_KEY: |-
            -----BEGIN PUBLIC KEY-----
            ADD YOUR PUBLIC KEY
            -----END PUBLIC KEY-----
        ADDITIONAL_PUBLIC_KEY: |-
            -----BEGIN PUBLIC KEY-----
            SECUNDARY PUBLIC KEY
            -----END PUBLIC KEY-----